#!/bin/bash
chown -R www:www /www
chown -R www:www /pma
chown -R www:www /log
chown -R www:www /usr/local/php
chown -R www:www /usr/local/nginx
chown -R mysql:mysql /data/mysql
chown -R redis:redis /data/redis
chown -R redis:redis /usr/local/redis

